### ISSUE TITLE
README - Author's name not linked

### ISSUE THREAD

**Issue by srvxid** [SoftwareEngineeringToolDemos/FSE-2013-RUBRIC#7]
Chetan Arora has a profile page at http://wwwen.uni.lu/snt/people/chetan_arora which is listed on the project page. This could be added in the readme.
Assigned to self.

**Comment by srvxid** [comment]
Pull request created.

**Comment by seelder** [comment]
This link was not formatted correctly, will need to update

**Comment by srvxid** [comment]
Pull request #9 fixes issue.
